// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://tqtrgmwhsxsuekddfzdb.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxdHJnbXdoc3hzdWVrZGRmemRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIyMjU3NDAsImV4cCI6MjA0NzgwMTc0MH0.1ZQXoG0PWRDuSmNlxmNFlNyY1R0obYbmqIVzQXWrEiw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);